# All 'dev' properties are centralized here
some.property=Development Configuration

# --- ALL DATABASE PROPERTIES GO HERE ---
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=UMed12345

# --- ALL JPA PROPERTIES GO HERE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
